### ISSUE TITLE
BUG: Searching for a TA makes the first section appear as a lecture

### ISSUE THREAD

**Issue by pconrad** [ucsb-cs156/proj-courses#26]
# User Story

* As a user
* I can search for courses including sections by instructor AND see accurate results
* So that I can search for courses by TA and not get confused.

### Discussion

In F19, CMPSC 56 was taught by `CONRAD P T ` teaching the lecture, and discussion sections led by  TAs `CHOW S P` and `SISCO Z D` as shown here.

<img width="1125" alt="image" src="https://github.com/ucsb-cs156/proj-courses/assets/1119017/37f1be67-e19b-40ef-b80f-fa3bf376c962">

If you do an instructor search on F19 for CONRAD, you get this. which is accurate.  Note that in this case, the CMPSC 56 line has no `+` to allow viewing the sections, since those were not taught by `CONRAD P T`

<img width="1179" alt="image" src="https://github.com/ucsb-cs156/proj-courses/assets/1119017/82570335-7a4f-44c1-9145-a8640cf43859">

However, if you search for `CHOW S P` for F19, you get this:

<img width="1170" alt="image" src="https://github.com/ucsb-cs156/proj-courses/assets/1119017/020ab666-1b5d-4db0-9c83-06d077dc7ee0">

This is confusing, because it format one of the three sections "as if" it is a lecture section.   Perhaps we may need a different component to display these results, or a different use of the component that is being used; but this isn't what we want.   

### Acceptance Criteria

Bug Fix:

- [ ] When a search includes discussion sections, either the lecture doesn't appear, or it appears with accurate information about the lecture section (even if that lecture isn't one of the search results.)

**Comment by vChase42** [comment]
See https://github.com/ucsb-cs156-s23/proj-courses-s23-7pm-2/pull/36
and
https://github.com/ucsb-cs156-s23/proj-courses-s23-7pm-2/pull/31
