### ISSUE TITLE
FEATURE: Change visual appearance to match UCSB standards

### ISSUE THREAD

**Issue by pconrad** [ucsb-cs156/proj-courses#28]
### Have you updated the title?

- [X] I have updated the issue's title.

### As a...

user

### I can...

see UCSB blue

### So that...

I experience a more professional looking site

### Discussion

The f22-7pm-courses team made a small change in the PR linked below that makes the site look much nicer.

In this issue, you'll apply their change to the current code base.

https://github.com/ucsb-cs156-f22/f22-7pm-courses/pull/31/files 

### Acceptance Criteria

- [ ] The navbar will show up in UCSB Blue

### Implementation Todos

See <https://github.com/ucsb-cs156-f22/f22-7pm-courses/pull/31/files>

The change to the .gitignore in that PR is unrelated and unnecessary (or if needed, should arguably go in a different PR.)

**Comment by vChase42** [comment]
Implemented from proj-courses-s23-7pm-3
