### ISSUE TITLE
BUG: Images don't show up reliably on localhost

### ISSUE THREAD

**Issue by pconrad** [ucsb-cs156/proj-courses#31]
### Summary

Images do not always show up reliably on localhost; they show up when deploying heroku or dokku, but not locally.

### Expected Behavior

Images should show up reliably whether on localhost or heroku/dokku.

### Current / Observed Behavior

Images don't always show up reliably on localhost.

### Steps to Reproduce

1. Display a page with a static image on localhost.
2. Note that it doesn't show up.

# Suggested approach to fix

See this PR: https://github.com/ucsb-cs156-s23/proj-gauchoride-s23-5pm-3/pull/34

**Comment by andrewpengucsb** [comment]
Solved by #53
